In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import glob
import trackpy as tp
import sys
sys.path.append('../../')

In [26]:
t1 = pd.read_csv('located_frames_Video1.csv')
t1=tp.link(t1,200, memory=400)
print('Before filtering:', t1['particle'].nunique())
t1f = tp.filter_stubs(t1, 300)
print('After filtering:', t1f['particle'].nunique())

Frame 33507: 10 trajectories present.
Before filtering: 11
After filtering: 10

In [9]:
t1f_p0 = t1f.query('particle == 0')
print(max(t1f_p0.frame))
print(max(t1f.frame))

In [27]:
pIDs = pd.unique(t1f['particle'])
for pID in pIDs:
    t1f_pID = t1f.query('particle == @pID')
    print(pID, min(t1f_pID.frame), max(t1f_pID.frame))

# are the they the same particle? 0,17,18 N10 lam03 video 1

0 1 33507
1 1 33507
2 1 33507
3 1 33507
4 1 33507
6 1 33507
7 1 33507
8 1 33507
9 1 33507
10 1 33507

In [ ]:
# some trial for n10 lam03 video 1
fig, ax = plt.subplots(1,1, figsize=(6,6))

t = t1f.query('particle == 0').iloc[-100:]
xmin, xmax = min(t.x), max(t.x)
ymin, ymax = min(t.y), max(t.y)
tp.plot_traj(t, colorby='frame', ax=ax, cmap='summer')


t = t1f.query('particle == 17').iloc[:100]
xmin = min(t.x) if xmin > min(t.x) else xmin
xmax = max(t.x) if xmax < min(t.x) else xmax
ymin = min(t.y) if ymin > min(t.y) else ymin
ymax = max(t.y) if ymax < max(t.y) else ymax
tp.plot_traj(t, colorby='frame', ax=ax)
ax.set(xlim=(xmin,xmax), ylim=(ymin,ymax))

In [40]:
t1f[t1f.frame == 1]

,y,x,mass,size,ecc,signal,raw_mass,ep,frame,particle
frame,,,,,,,,,,
1,115.682270,1007.602013,19078.988347,6.058168,0.059913,144.017352,24448.0,0.0,1,0
1,227.176499,758.761246,18546.786295,4.920662,0.082862,180.435532,22458.0,0.0,1,1
1,315.848883,1394.297301,17450.102439,4.589469,0.118657,206.921482,20732.0,0.0,1,2
1,388.659144,952.342834,17162.895421,4.783261,0.026274,192.023136,20450.0,0.0,1,3
1,459.114051,1169.285701,17301.118972,4.777387,0.026146,183.746276,21110.0,0.0,1,4
1,706.447427,910.024767,21922.917198,4.835658,0.039649,195.333879,26516.0,0.0,1,6
1,713.989311,1004.266972,20055.657743,5.386050,0.008700,201.955367,25262.0,0.0,1,7
1,838.169745,1210.874796,19270.183796,6.842758,0.045732,133.257435,25937.0,0.0,1,8
1,900.312477,1071.130957,17924.366476,4.794710,0.040392,211.059912,21712.0,0.0,1,9
1,1015.599197,824.570136,22044.587030,7.566436,0.080885,144.845038,31933.0,0.0,1,10